
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";     
    
//core
import "primereact/resources/primereact.min.css"; 


import 'primeicons/primeicons.css';
        

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Validador numeros celulares',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
